# This configuration corresponds to Ablation study
# NOTE: the predicted trajectory is not in the real-world scale.

#-------------------------------------
#- Basic setup
#-------------------------------------
dataset: kitti_odom                                       # dataset [kitti_odom, kitti_raw, tum-1/2/3, adelaide1/2]
seed: 4869                                                # random seed
image:
    height: 192                                           # image height
    width: 640                                            # image width
    ext: .png                                              # image file extension for data loading
seq: "10"                                                 # sequence to run
frame_step: 1                                             # frame step
cam_mode: mono                                            # camera mode: [mono, stereo]

batch_size: 1             
num_workers: 0   
split: odom 
backbone: convnext_large
model_dim: 64
dec_channels: [1024, 512, 256, 128]


#-------------------------------------
#- Directories
#-------------------------------------
directory:
    result_dir: /poolz2/fanliang/DF-VO/result/posenet/0/                             # directory to save result
    img_seq_dir: /poolz2/fanliang/kitti_odom/data_odometry_color/dataset/        # image data directory
    gt_pose_dir: /poolz2/fanliang/DF-VO/dataset/kitti_odom/gt_poses/             # (optional) ground-truth pose data directory
    depth_dir:                                            # (optional) external depth data, e.g. ground-truth depths

#-------------------------------------
#- PoseNet
#-------------------------------------
PoseNet:                                                              # PoseNet configuration
    model_pth: /home/rdfzzt/tmp/mdp/models/epoch_1/pose.pth     # directory stores pose.pth

#-------------------------------------
#- Encoder
#-------------------------------------
Encoder:                                                              # Encoder configuration
    model_pth: /home/rdfzzt/tmp/mdp/models/epoch_1/encoder.pth     # directory stores encoder.pth

#-------------------------------------
#- Depth
#-------------------------------------
depth:                                                    # Depth configuration
    depth_src:                                            # depth source [None, gt]